Clasificación - Predecir si vive o muere una persona.

In [100]:
import pandas as pd

titanic_train = pd.read_csv("train.csv")
titanic_test = pd.read_csv("test.csv")

titanic = pd.concat([titanic_train, titanic_test])

In [101]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [102]:
titanic = titanic.drop(columns=["PassengerId", "Name", "Cabin"])

In [103]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    float64
 1   Pclass    1309 non-null   int64
 2   Sex       1309 non-null   object
 3   Age       1046 non-null   float64
 4   SibSp     1309 non-null   int64
 5   Parch     1309 non-null   int64
 6   Ticket    1309 non-null   object
 7   Fare      1308 non-null   float64
 8   Embarked  1307 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 102.3+ KB

In [104]:
titanic.isnull().sum()

Survived    418
Pclass        0
Sex           0
Age         263
SibSp         0
Parch         0
Ticket        0
Fare          1
Embarked      2
dtype: int64

In [105]:
titanic = titanic.dropna()

In [106]:
titanic.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [107]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  712 non-null    float64
 1   Pclass    712 non-null    int64
 2   Sex       712 non-null    object
 3   Age       712 non-null    float64
 4   SibSp     712 non-null    int64
 5   Parch     712 non-null    int64
 6   Ticket    712 non-null    object
 7   Fare      712 non-null    float64
 8   Embarked  712 non-null    object
dtypes: float64(3), int64(3), object(3)
memory usage: 55.6+ KB

In [108]:
titanic.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0.0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1.0,1,female,38.0,1,0,PC 17599,71.2833,C
2,1.0,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1.0,1,female,35.0,1,0,113803,53.1000,S
4,0.0,3,male,35.0,0,0,373450,8.0500,S

In [109]:
#titanic = pd.get_dummies(titanic, dtype=int, columns=["Sex", "Embarked"])

In [ ]:
titanic['Ticket'] = titanic['Ticket'].str.replace('[a-zA-Z/.]', '', regex=True)
titanic['Ticket'] = titanic['Ticket'].str.replace(r'\s', '', regex=True)
# Después de tu limpieza...
df['columna'] = df['columna'].replace('', np.nan)
df['columna'] = df['columna'].astype(float)

In [122]:
titanic = pd.get_dummies(titanic, dtype=int, columns=titanic.select_dtypes(include=['object']).columns.difference(['Ticket']))

In [127]:
titanic.head()

,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male
0,0.0,3,22.0,1,0,521171,7.2500,0,0,1,0,1
1,1.0,1,38.0,1,0,17599,71.2833,1,0,0,1,0
2,1.0,3,26.0,0,0,23101282,7.9250,0,0,1,1,0
3,1.0,1,35.0,1,0,113803,53.1000,0,0,1,1,0
4,0.0,3,35.0,0,0,373450,8.0500,0,0,1,0,1

In [128]:
titanic.corr(numeric_only=False)['Survived'].abs().sort_values(ascending=False)[1:]

ValueError: could not convert string to float: ''