EJERCICIO 1: Marketing Campaign
- Celda 1: Importar librerías
- Importar las librerías necesarias (pandas, numpy, datetime)

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import datetime as dt

Celda 2: Ejercicio 1.1 - Importar CSV
- Importa el csv adjunto con el examen, de nombre "marketing_campaign.csv", en un DataFrame. Debes usar el parámetro sep='\t' porque no usa ; sino tabulaciones para separar los datos.
- Verificar que se importó correctamente mostrando las primeras filas y las dimensiones.

In [17]:
marketing = pd.read_csv("marketing_campaign.csv", sep='\t')

marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

Celda 3: Ejercicio 1.2 - Convertir a Datetime y filtrar los 1000 más modernos
- Cambia la columna dt_customer a formato Datetime y quédate con los 1000 clientes más modernos. El cambio debe ser permanente y usarlo a partir de aquí en todo el examen, salvo que se indique lo contrario.
- Verificar el número de filas después del filtro y mostrar algunos valores de dt_customer.

In [18]:
marketing["Dt_Customer"] = pd.to_datetime(marketing["Dt_Customer"],dayfirst=True)
#marketing = marketing.sort_values(by="Dt_Customer", ascending=False).head(1000)
marketing = marketing.sort_values(by="Dt_Customer", ascending=False).iloc[:1000]

marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
200,7300,1952,Graduation,Divorced,69142,0,1,2014-06-29,50,448,...,5,0,1,0,0,0,0,3,11,0
989,453,1956,PhD,Widow,35340,1,1,2014-06-29,1,27,...,5,0,0,0,0,0,0,3,11,0
1812,8093,1969,Master,Married,79734,0,0,2014-06-28,72,572,...,1,0,0,0,1,0,0,3,11,0
796,6722,1954,PhD,Married,70421,0,1,2014-06-28,98,479,...,6,0,0,0,0,0,0,3,11,0
45,1371,1976,Graduation,Single,79941,0,0,2014-06-28,72,123,...,1,0,0,0,0,0,0,3,11,0

In [19]:
marketing.shape

(1000, 29)

In [ ]:
marketing["Dt_Customer"]

200    2014-06-29
989    2014-06-29
1812   2014-06-28
796    2014-06-28
45     2014-06-28
          ...
1763   2013-08-20
1268   2013-08-20
1666   2013-08-20
610    2013-08-19
966    2013-08-19
Name: Dt_Customer, Length: 1000, dtype: datetime64[ns]

Celda 4: Ejercicio 1.3 - Columna "Probably_Died"
- Recorre el dataframe para generar una columna nueva llamada "Probably_Died". El valor de esta columna será True en los casos en los que el cliente haya nacido hace más de 100 años. False en el resto de los casos. Recuerda hacerlo recorriendo el dataframe.
- Verificar mostrando algunas filas y contando cuántos clientes probablemente murieron.

In [21]:
marketing["Year_Birth"].astype(int)

200     1952
989     1956
1812    1969
796     1954
45      1976
        ...
1763    1977
1268    1948
1666    1967
610     1969
966     1973
Name: Year_Birth, Length: 1000, dtype: int64

In [25]:
type(marketing["Year_Birth"])

pandas.core.series.Series

In [43]:
Probably_Died = []

for index, row in marketing.iterrows():
    if row["Year_Birth"] < 1926:
        Probably_Died.append(True)
    else:
        Probably_Died.append(False)

marketing["Probably_Died"] = Probably_Died

marketing.head(50)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died,new_column
200,7300,1952,Graduation,Divorced,69142,0,1,2014-06-29,50,448,...,1,0,0,0,0,3,11,0,False,452
989,453,1956,PhD,Widow,35340,1,1,2014-06-29,1,27,...,0,0,0,0,0,3,11,0,False,27
1812,8093,1969,Master,Married,79734,0,0,2014-06-28,72,572,...,0,0,1,0,0,3,11,0,False,580
796,6722,1954,PhD,Married,70421,0,1,2014-06-28,98,479,...,0,0,0,0,0,3,11,0,False,507
45,1371,1976,Graduation,Single,79941,0,0,2014-06-28,72,123,...,0,0,0,0,0,3,11,0,False,287
1587,2471,1965,Graduation,Married,61482,0,0,2014-06-27,39,48,...,0,0,0,0,0,3,11,0,False,106
1800,2831,1976,Graduation,Together,78416,0,1,2014-06-27,99,453,...,0,0,0,0,0,3,11,0,False,491
706,4472,1970,PhD,Divorced,35682,1,0,2014-06-27,34,23,...,0,0,0,0,0,3,11,0,False,23
2199,9014,1975,Graduation,Married,37085,1,1,2014-06-26,65,39,...,0,0,0,0,0,3,11,0,False,40
463,7059,1963,Graduation,Married,80124,0,0,2014-06-26,47,483,...,0,0,0,0,0,3,11,0,False,567
2054,6382,1953,Graduation,Together,48794,1,1,2014-06-26,97,25,...,0,0,0,0,0,3,11,0,False,25
266,1225,1963,Graduation,Married,80124,0,0,2014-06-26,47,483,...,0,0,0,0,0,3,11,0,False,567
1455,4399,1969,Graduation,Together,68695,0,0,2014-06-25,3,458,...,0,0,0,0,0,3,11,0,False,539
1032,9888,1969,Graduation,Together,68695,0,0,2014-06-25,3,458,...,0,0,0,0,0,3,11,0,False,539
2223,1448,1963,Master,Married,33562,1,2,2014-06-25,33,21,...,0,0,0,0,0,3,11,0,False,33
964,5633,1980,Graduation,Married,50183,1,1,2014-06-25,47,97,...,0,0,0,0,0,3,11,0,False,109
112,3267,1963,Master,Together,57288,0,1,2014-06-25,27,527,...,1,0,0,0,0,3,11,0,False,527
1023,4550,1966,Master,Together,33564,0,1,2014-06-24,51,61,...,0,0,0,0,0,3,11,0,False,61
178,10492,1959,Graduation,Together,38285,2,1,2014-06-24,96,2,...,0,0,0,0,0,3,11,0,False,2
1659,2781,1981,Graduation,Single,72066,0,0,2014-06-23,55,1003,...,0,1,1,0,0,3,11,1,False,1037
1846,9931,1963,PhD,Married,4023,1,1,2014-06-23,29,5,...,0,0,0,0,0,3,11,0,False,5
981,3955,1965,Graduation,Divorced,4861,0,0,2014-06-22,20,2,...,0,0,0,0,0,3,11,0,False,3
994,1640,1954,Graduation,Divorced,64587,1,1,2014-06-22,49,66,...,0,0,0,0,0,3,11,0,False,66
1920,2546,1977,2n Cycle,Single,31878,0,1,2014-06-22,7,23,...,0,0,0,0,0,3,11,0,False,27
2052,2591,1959,Graduation,Widow,76320,0,1,2014-06-22,49,526,...,0,0,0,0,0,3,11,0,False,561
1486,2939,1970,Master,Together,79419,0,0,2014-06-22,96,751,...,0,0,0,0,0,3,11,0,False,878
1269,9400,1958,2n Cycle,Single,85485,0,0,2014-06-21,73,630,...,0,0,0,0,0,3,11,0,False,656
149,4050,1966,Master,Married,49605,0,0,2014-06-21,65,42,...,0,0,0,0,0,3,11,0,False,58
2124,2115,1957,Graduation,Together,50116,1,1,2014-06-20,68,54,...,1,0,0,0,0,3,11,0,False,54
1947,2495,1974,Master,Married,83891,0,1,2014-06-20,24,217,...,0,0,0,0,0,3,11,0,False,255
883,8017,1981,2n Cycle,Married,51111,1,1,2014-06-19,83,22,...,0,0,0,0,0,3,11,0,False,22
1106,6271,1952,PhD,Married,50870,0,1,2014-06-19,13,53,...,0,0,0,0,0,3,11,0,False,53
1638,10785,1969,Graduation,Married,44078,1,1,2014-06-19,17,24,...,0,0,0,0,0,3,11,0,False,25
1020,5287,1973,Graduation,Married,34961,1,0,2014-06-19,77,45,...,0,0,0,0,0,3,11,0,False,47
1563,4828,1954,Graduation,Divorced,79865,0,1,2014-06-18,12,71,...,0,0,0,0,0,3,11,0,False,170
1463,10403,1978,Graduation,Together,16531,1,0,2014-06-18,43,2,...,0,0,0,0,0,3,11,0,False,15
532,4769,1977,Master,Together,57954,1,1,2014-06-18,52,456,...,1,0,0,0,0,3,11,0,False,460
262,4200,1970,Master,Married,44159,1,0,2014-06-17,85,167,...,0,0,0,0,0,3,11,0,False,169
1710,477,1986,Graduation,Married,83512,0,0,2014-06-17,31,1060,...,0,1,1,1,0,3,11,1,False,1121
1962,6355,1978,Graduation,Married,44359,1,1,2014-06-17,19,20,...,0,0,0,0,0,3,11,0,False,20
347,1826,1970,Graduation,Divorced,84835,0,0,2014-06-16,0,189,...,0,0,0,0,0,3,11,1,False,293
1647,7005,1981,Graduation,Single,58684,0,0,2014-06-16,71,479,...,1,0,0,0,0,3,11,0,False,514
1766,10560,1980,PhD,Single,36802,1,0,2014-06-16,23,16,...,0,0,0,0,0,3,11,0,False,17
1564,10699,1985,Graduation,Married,44322,1,0,2014-06-16,30,46,...,0,0,0,0,0,3,11,0,False,46
1819,8566,1961,PhD,Together,32583,1,1,2014-06-15,10,5,...,0,0,0,0,0,3,11,0,False,5
1768,8312,1961,Basic,Married,28249,0,0,2014-06-15,80,1,...,0,0,0,0,0,3,11,0,False,10
184,2563,1961,Basic,Married,28249,0,0,2014-06-15,80,1,...,0,0,0,0,0,3,11,0,False,10
822,1,1961,Graduation,Single,57091,0,0,2014-06-15,0,464,...,0,0,0,1,0,3,11,1,False,469
1532,3463,1975,PhD,Married,69283,0,1,2014-06-14,41,674,...,0,0,0,0,0,3,11,0,False,736
631,9624,1958,PhD,Together,65488,0,0,2014-06-13,46,603,...,0,0,0,0,0,3,11,0,False,648

In [53]:
conteo = 0
for index, row in marketing.iterrows():
    if row['Probably_Died'] == True:
        conteo += 1
    else:
        None

print(f"Probablemente han muerto: {conteo} personas")

Probablemente han muerto: 3 personas

In [50]:
print((marketing["Probably_Died"] == False ).sum())

997

Celda 5: Ejercicio 1.4 - Función new_column
- Crea una función (llamada new_column) que reciba un dataframe y devuelva un pandas Series con la suma de las columnas MntWines y MntFruits.
- Probar la función y verificar que devuelve un pandas Series.

In [63]:
def new_column (df):
    pd_series = df["MntWines"] + df["MntFruits"]
    return pd_series

#marketing["new_column"] = suma
print(new_column(marketing))
#type(marketing)
#new_column(marketing)
#marketing.head()

200     452
989      27
1812    580
796     507
45      287
       ...
1763    727
1268    146
1666    623
610     114
966     714
Length: 1000, dtype: int64

Celda 6: Ejercicio 1.5 - Convertir Education a numérica
- Convierte la columna Education para que sea numérica. Para ello debes usar df['Education'].unique() que te devolverá todos los valores únicos de la columna. Asigna un valor numérico a cada valor posible de la columna y sustituye en la columna todos por esos números. Por ejemplo, siempre que ponga Master, puedes poner un 2 (o cualquier otro número).
- Mostrar los valores únicos antes y después de la conversión.

In [67]:
marketing["Education"].unique()
marketing["Education"].replace({
    'Graduation': 1,
    'PhD': 2,
    'Master': 3,
    '2n Cycle': 4,
    'Basic': 5
}, inplace=True)

marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died,new_column
200,7300,1952,1,Divorced,69142,0,1,2014-06-29,50,448,...,1,0,0,0,0,3,11,0,False,452
989,453,1956,2,Widow,35340,1,1,2014-06-29,1,27,...,0,0,0,0,0,3,11,0,False,27
1812,8093,1969,3,Married,79734,0,0,2014-06-28,72,572,...,0,0,1,0,0,3,11,0,False,580
796,6722,1954,2,Married,70421,0,1,2014-06-28,98,479,...,0,0,0,0,0,3,11,0,False,507
45,1371,1976,1,Single,79941,0,0,2014-06-28,72,123,...,0,0,0,0,0,3,11,0,False,287

In [68]:
marketing["Education"].unique()

array([1, 2, 3, 4, 5])

Celda 7: Ejercicio 1.6 - Nuevo DataFrame VIP_clients
- Filtra el dataframe para guardar uno nuevo, llamado VIP_clients. En él tienen que figurar solo los clientes que tengan MntWines mayor que 400 e income mayor que 80000. Cuando te encuentres problemas, los tienes que solucionar usando el propio dataframe, no directamente en el csv. Dependiendo de como lo quieras hacer puede que tengas que comprobar el tipo de algún objeto. Dicha comparación se hace así: type(objeto) == str
- Verificar el número de clientes VIP y mostrar algunas filas.

In [ ]:

'''
VIP_clients = []
for index, row in marketing.iterrows():
    if marketing["MntWines"] > 400 & marketing["Income"] > 80000:
        VIP_clients.append

marketing["Probably_Died"] = Probably_Died
'''

In [98]:
marketing.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
Probably_Died          0
new_column             0
dtype: int64

In [ ]:
# Eliminar nulos
filas_a_eliminar = []
for index, row in marketing.iterrows():
    if pd.isna(row['Income']):
        filas_a_eliminar.append(index)

marketing = marketing.drop(filas_a_eliminar)

In [ ]:

incomes = []
for index,row in marketing.iterrows():
    # si el valor de una fila income es string
    if (type(row['Income']) == str):
        # metemos en la lista ese valor de income quitando las comas y en formato float
        incomes.append(float(row['Income'].replace(",","")))
    else:
        # si no es string lo metemos igual
        incomes.append(row['Income'])

# igualamos las filas income a los valores de la lista
marketing['Income'] = incomes

In [ ]:
VIP_clients = marketing.loc[(marketing["MntWines"] > 400) & (marketing["Income"] > 80000)]

VIP_clients.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died,new_column
463,7059,1963,1,Married,80124.0,0,0,2014-06-26,47,483,...,0,0,0,0,0,3,11,0,False,567
266,1225,1963,1,Married,80124.0,0,0,2014-06-26,47,483,...,0,0,0,0,0,3,11,0,False,567
1269,9400,1958,4,Single,85485.0,0,0,2014-06-21,73,630,...,0,0,0,0,0,3,11,0,False,656
1710,477,1986,1,Married,83512.0,0,0,2014-06-17,31,1060,...,0,1,1,1,0,3,11,1,False,1121
53,2225,1977,1,Divorced,82582.0,0,0,2014-06-07,54,510,...,0,0,1,0,0,3,11,1,False,630

EJERCICIO 2: NBA Dataset
Celda 8: Ejercicio 2.1 - Importar CSV NBA
- Importa el csv adjunto con el examen, de nombre "nba.csv" pasándolo a un DataFrame.
- Verificar mostrando las primeras filas, dimensiones y nombres de columnas.

In [121]:
nba = pd.read_csv("nba.csv")

nba.head(30)
nba.shape

(30, 25)

Celda 9: Ejercicio 2.2 - Filtrar equipos con más de 45 partidos y 13 triples
- Filtra el dataframe y quédate solo con los equipos que tienen más de 45 partidos jugados (G) y más de 13 triples por partido (3P)
- Verificar el número de equipos después del filtro y mostrar algunas filas.

In [123]:
nba.loc[(nba["G"] > 45) & (nba["3P"] > 13)]
#nba_filtrado = nba.loc[(nba["G"] > 45) & (nba["3P"] > 13)]
#nba_filtrado.shape

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Utah Jazz,47,240.0,40.7,86.3,0.472,14.7,40.6,0.362,...,0.780,10.3,36.3,46.6,22.2,6.9,4.9,14.1,18.9,114.2
1,2,Charlotte Hornets,47,242.1,42.5,92.3,0.461,14.0,38.2,0.367,...,0.736,10.6,33.9,44.4,27.1,8.8,5.1,13.1,19.3,114.1
4,5,Milwaukee Bucks,49,241.0,40.4,89.2,0.454,14.3,39.5,0.362,...,0.778,10.4,36.8,47.2,23.0,7.7,4.4,13.8,17.9,112.0
8,9,Minnesota Timberwolves,46,241.6,40.4,91.6,0.441,14.3,41.7,0.343,...,0.759,12.4,32.8,45.2,24.5,8.8,5.8,15.1,22.1,111.0
12,13,Golden State Warriors,47,241.1,39.9,86.2,0.463,14.1,39.8,0.354,...,0.756,9.9,36.4,46.3,27.5,9.5,5.0,15.6,20.3,109.4
13,14,Miami Heat,47,241.1,39.4,85.5,0.460,13.5,36.0,0.376,...,0.807,10.8,33.7,44.5,25.7,7.3,3.3,14.4,20.1,108.6
14,15,Portland Trail Blazers,46,240.5,38.8,86.7,0.448,13.6,37.9,0.359,...,0.770,10.1,33.7,43.8,22.7,7.7,4.8,14.0,19.9,108.4
15,16,Houston Rockets,47,240.5,38.7,85.7,0.452,13.3,38.4,0.347,...,0.717,9.5,33.6,43.1,22.9,7.3,4.8,16.9,20.1,108.3

Celda 10: Ejercicio 2.3 - Equipos con mal cálculo de puntos
- Muestra el nombre de los equipos que tienen mal calculados los puntos por partido. Es decir, que no coincida la columna de puntos por partido (PTS) con el cálculo: 3*3P + 2*2P + FT
- Crear una columna con los puntos calculados según la fórmula y mostrar los equipos donde no coincide.

In [ ]:
equipos = []
Puntos_Calculados = nba["3P"]*3 + nba["2P"]*2 + nba["FT"]

for index, row in nba.iterrows():
    calculado = row["3P"]*3 + row["2P"]*2 + row["FT"]
    if row["PTS"] != calculado:
        equipos.append(row["Team"])

nba["Puntos_Calculados"] = Puntos_Calculados

nba.head()

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Puntos_Calculados
0,1,Utah Jazz,47,240.0,40.7,86.3,0.472,14.7,40.6,0.362,...,10.3,36.3,46.6,22.2,6.9,4.9,14.1,18.9,114.2,114.4
1,2,Charlotte Hornets,47,242.1,42.5,92.3,0.461,14.0,38.2,0.367,...,10.6,33.9,44.4,27.1,8.8,5.1,13.1,19.3,114.1,114.0
2,3,Phoenix Suns,45,240.6,42.5,89.4,0.476,11.5,31.7,0.363,...,10.0,36.0,46.0,26.4,8.8,4.2,13.5,19.5,112.5,112.4
3,4,Brooklyn Nets,46,241.1,41.8,88.2,0.474,11.1,31.7,0.352,...,9.8,35.5,45.3,25.6,7.0,5.5,14.2,20.1,112.2,112.1
4,5,Milwaukee Bucks,49,241.0,40.4,89.2,0.454,14.3,39.5,0.362,...,10.4,36.8,47.2,23.0,7.7,4.4,13.8,17.9,112.0,112.1

In [146]:
print("Equipos con error:")
print(len(equipos))

Equipos con error:
24

In [147]:
print(len(nba["Team"]))

30

Celda 11: Ejercicio 2.4 - Eliminar columnas y mostrar correlación
- En un dataframe nuevo quita las columnas Rk, Team y PTS. Después, muestra la matriz de correlación solo de la columna 2P. Muestra los 5 que mayor correlación tengan.

In [151]:
nba_nuevo = nba.drop(columns=["Rk", "Team", "PTS"])

nba_nuevo.head()

,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,Puntos_Calculados
0,47,240.0,40.7,86.3,0.472,14.7,40.6,0.362,26.1,45.7,...,0.780,10.3,36.3,46.6,22.2,6.9,4.9,14.1,18.9,114.4
1,47,242.1,42.5,92.3,0.461,14.0,38.2,0.367,28.5,54.1,...,0.736,10.6,33.9,44.4,27.1,8.8,5.1,13.1,19.3,114.0
2,45,240.6,42.5,89.4,0.476,11.5,31.7,0.363,31.0,57.7,...,0.805,10.0,36.0,46.0,26.4,8.8,4.2,13.5,19.5,112.4
3,46,241.1,41.8,88.2,0.474,11.1,31.7,0.352,30.7,56.6,...,0.827,9.8,35.5,45.3,25.6,7.0,5.5,14.2,20.1,112.1
4,49,241.0,40.4,89.2,0.454,14.3,39.5,0.362,26.2,49.7,...,0.778,10.4,36.8,47.2,23.0,7.7,4.4,13.8,17.9,112.1

In [155]:
nba["2P"].sort_values(ascending=False).head(5).corr

<bound method Series.corr of 10    32.0
5     31.0
2     31.0
3     30.7
18    30.1
Name: 2P, dtype: float64>