In [2]:
import pandas as pd

adultos = pd.read_csv("adult.csv")

In [3]:
adultos.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [5]:
columnas_objetivo = [
    "age",
    "fnlwgt",
    "education.num",
    "capital.gain",
    "capital.loss",
    "hours.per.week",
    "income"
]

df_modelo = adultos[columnas_objetivo]

df_modelo.tail()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,income
32556,22,310152,10,0,0,40,<=50K
32557,27,257302,12,0,0,38,<=50K
32558,40,154374,9,0,0,40,>50K
32559,58,151910,9,0,0,40,<=50K
32560,22,201490,9,0,0,20,<=50K

In [7]:
df_modelo["income"] = df_modelo["income"].replace ({ 
    "<=50K": 1,
    ">50K": 2
}).astype(int)

/tmp/ipykernel_35923/372171061.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_modelo["income"] = df_modelo["income"].replace ({
/tmp/ipykernel_35923/372171061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modelo["income"] = df_modelo["income"].replace ({

In [8]:
df_modelo.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,income
0,90,77053,9,0,4356,40,1
1,82,132870,9,0,4356,18,1
2,66,186061,10,0,4356,40,1
3,54,140359,4,0,3900,40,1
4,41,264663,10,0,3900,40,1

In [9]:
df_modelo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   fnlwgt          32561 non-null  int64
 2   education.num   32561 non-null  int64
 3   capital.gain    32561 non-null  int64
 4   capital.loss    32561 non-null  int64
 5   hours.per.week  32561 non-null  int64
 6   income          32561 non-null  int64
dtypes: int64(7)
memory usage: 1.7 MB

In [10]:
X = pd.DataFrame(df_modelo.data, columns=df_modelo.feature_names)
y = pd.Series(df_modelo.target, name='income')

AttributeError: 'DataFrame' object has no attribute 'data'