# Examen 11/12/2025: Evaluación 1 Examen 1: Python

<div style="border-style:groove;border-width:thin;padding:10px">
    <h3>NORMAS:</h3>
    <ul>
        <li>No se dispondrá de Internet durante el examen. Se podrá usar cualquier material descargado o en papel.</li>
        <li>Queda prohibida cualquier comunicación entre vosotros o con el exterior.</li>
        <li>Deberá grabarse toda la sesión desde antes de recibir el examen hasta después de entregarlo utilizando OBS de forma local. La grabación se entregará a la vez que el examen. Quedan prohibidos los atajos de teclado del OBS</li> 
        <li>No se puede utilizar ninguna herramienta que asista a la programación. Ni basada en IA ni de otro tipo. Tampoco se podrá usar material hecho con IA.</li>
        <li>No se permite el uso de funciones genéricas que atajen distintos tipos de problemas. Solo se valorarán las soluciones concretas a lo que se pregunta.</li>
        <li>La entrega del examen se hará supervisada por el profesor y se anotará la hora exacta de entrega.</li>
        <li>Los móviles permanecerán durante toda la sesión sobre los PCs colocados con la pantalla hacia abajo.</li>
    </ul>
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
    <p><b>Ejercicio 1:</b></p>
    <ol>
        <li>Importa el csv adjunto con el examen, de nombre "marketing_campaign.csv", en un DataFrame. Debes usar el parámetro sep='\t' porque no usa ; sino tabulaciones para serparar los datos.</li>
        <li>Cambia la columna dt_customer a formato Datetime y quédate con los 1000 clientes más modernos. El cambio debe ser permanente y usarlo a partir de aquí en todo el examen, salvo que se indique lo contrario.</li>
        <li>Recorre el dataframe para generar una columna nueva llamada "Probably_Died". El valor de está columna será True en los casos en los que el cliente haya nacido hace más de 100 años. False en el resto de los casos. Recuerda hacerlo recorriendo el dataframe.</li>
        <li>Crea una función (llamada new_column) que reciba un dataframe y devuelva un pandas Series con la suma de las columnas MntWines y MntFruits.</li>
        <li>Convierte la columna Education para que sea numérica. Para ello debes usar df['Education'].unique() que te devolverá todos los valores únicos de la columna. Asigna un valor numérico a cada valor posible de la columna y sustituye en la columna todos por esos números. Por ejemplo, siempre que ponga Master, puedes poner un 2 (o cualquier otro número). </li>
        <li>Filtra el dataframe para guardar uno nuevo, llamado VIP_clients. En el tienen que figurar solo los clientes que tengan MntWines mayor que 400 e income mayor que 80000. Cuando te encuentres problemas, los tienes que solucionar usando el propio dataframe, no directamente en el csv. Dependiendo de como lo quieras hacer puede que tengas que comprobar el tipo de algún objeto. Dicha comparación se hace así: type(objeto) == str</li>
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
    <p><b>Ejercicio 2:</b></p>
    <ol>
        <li>Importa el csv adjunto con el examen, de nombre "nba.csv" pasándolo a un DataFrame.</li>
        <li>Filtra el dataframe y quédate solo con los equipos que tinen más de 45 partidos jugados (G) y más de 13 triples por partido (3P)</li>
        <li>Muestra el nombre de los equipos que tienen mal calculados los puntos por partido. Es decir, que no coincida la columna de puntos por partido (PTS) con el cálculo: 3*3P + 2*2P + FT</li>
        <li>En un dataframe nuevo quita las columnas Rk, Team y PTS. Después, muestra la matriz de correlación solo de la columna 2P. Muestra los 5 que mayor correlación tengan. </li>
</div>

Criterio de calificación: 

Cada ejercicio y opción debidamente desarrollada se califica con los puntos especificados en la siguiente tabla. La suma de los puntos calificados para cada opción será la calificación de la prueba:


| Apartado | Calificación máxima | Calificación obtenida |
| :-- | --- | --- |
| Ej. 1.2. Cambio a Datetime y quedarse con los 1000 más modernos. | 0,5 |  |
| Ej. 1.3. Nueva columna con Probably_Died. | 2 |  |
| Ej. 1.4. Función new_column. | 0,5 |  |
| Ej. 1.5. Education a numérica. | 2 |  |
| Ej. 1.6. Nuevo Dataframe Vip_Clients. | 2 |  |
| Ej. 2.2. Más de 45 partidos jugados y 13 triples.  | 1 |  |
| Ej. 2.3. Mal los puntos por partido. | 1 |  |
| Ej. 2.4. Quitar columnas y correlación. | 1 |  |

In [2]:
#1.1
import pandas as pd
marketing = pd.read_csv('marketing_campaign.csv',sep='\t')
marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [3]:
#1.2 Cambia la columna dt_customer a formato Datetime y quédate con los 1000 clientes más modernos. 
# El cambio debe ser permanente y usarlo a partir de aquí en todo el examen.
import datetime
marketing['Dt_Customer'] = pd.to_datetime(marketing['Dt_Customer'],dayfirst=True)
marketing = marketing.sort_values(by='Dt_Customer',ascending=False).iloc[:1000]

In [4]:
#1.3 Recorre el dataframe para generar una columna nueva llamada "Probably_Died". 
# El valor de está columna será True en los casos en los que el cliente haya nacido 
# hace más de 100 años. False en el resto de los casos.
probably_died = []
for index,row in marketing.iterrows():
    if row['Year_Birth'] < 1925:
        probably_died.append(True)
    else:
        probably_died.append(False)
marketing['Probably_Died'] = probably_died
marketing.sort_values(by='Year_Birth',ascending=True).head(20)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died
239,11004,1893,2n Cycle,Single,60182,0,1,2014-05-17,23,8,...,0,0,0,0,0,0,3,11,0,True
339,1150,1899,PhD,Together,83532,0,0,2013-09-26,36,755,...,0,0,1,0,0,0,3,11,0,True
192,7829,1900,2n Cycle,Divorced,36640,1,0,2013-09-26,99,15,...,0,0,0,0,0,1,3,11,0,True
358,6142,1943,Master,Married,65073,0,0,2013-08-20,65,629,...,0,0,0,0,0,1,3,11,0,False
1923,4994,1943,Master,Single,77598,0,0,2013-10-01,53,1193,...,0,0,1,0,0,0,3,11,0,False
415,7106,1943,PhD,Married,75865,0,0,2014-03-31,73,483,...,0,0,0,0,0,0,3,11,0,False
2084,5250,1943,Master,Widow,NaN,0,0,2013-10-30,75,532,...,0,0,1,0,0,0,3,11,1,False
1270,1740,1944,Graduation,Married,55956,0,0,2014-04-07,22,760,...,0,1,0,0,0,0,3,11,0,False
494,6605,1944,PhD,Divorced,55614,0,0,2013-11-27,85,504,...,0,1,0,0,0,0,3,11,0,False
1413,4310,1944,Graduation,Married,80589,0,0,2014-01-22,25,507,...,0,0,0,1,0,0,3,11,1,False
803,9930,1944,PhD,Single,82716,0,0,2013-11-05,8,606,...,0,0,0,0,0,0,3,11,0,False
519,3711,1944,Master,Married,80184,0,0,2014-03-01,19,1035,...,0,0,1,1,0,0,3,11,0,False
1898,4619,1945,PhD,Single,113734,0,0,2014-05-28,9,6,...,0,0,0,0,0,0,3,11,0,False
1329,158,1945,PhD,Together,71604,0,0,2013-11-17,3,345,...,1,0,0,0,0,0,3,11,1,False
1637,10711,1945,Graduation,Married,69755,0,0,2013-10-02,23,217,...,0,0,0,0,0,0,3,11,0,False
1742,263,1945,PhD,Single,45576,0,0,2014-05-28,9,56,...,0,0,0,0,0,0,3,11,1,False
1144,819,1945,Graduation,Widow,63285,0,0,2013-11-05,84,508,...,0,0,0,0,0,0,3,11,0,False
1487,5529,1946,PhD,Together,64014,2,1,2014-06-10,56,406,...,0,0,0,1,0,0,3,11,0,False
1444,1553,1946,Graduation,Together,82657,0,0,2013-09-27,71,966,...,0,1,0,1,0,0,3,11,0,False
182,10562,1946,Master,Married,66835,0,0,2013-09-28,21,620,...,0,0,0,0,0,0,3,11,0,False

In [5]:
marketing[['MntWines','MntFruits']]

      MntWines  MntFruits
200        448          4
989         27          0
1812       572          8
796        479         28
45         123        164
...        ...        ...
1763       707         20
1268       145          1
1666       593         30
610        101         13
966        693         21

[1000 rows x 2 columns]

In [6]:
#1.4 Crea una función (llamada new_column) que reciba un dataframe y devuelva un pandas Series
#  con la suma de las columnas MntWines	MntFruits.
def new_column (df):
    pd_series = df['MntWines'] + df['MntFruits']
    return pd_series

print(new_column(marketing))

200     452
989      27
1812    580
796     507
45      287
       ...
1763    727
1268    146
1666    623
610     114
966     714
Length: 1000, dtype: int64

In [7]:
#1.5 Convierte la columna Education para que sea numérica.
# Para ello debes usar df['Education'].unique() que te devolverá todos los valores únicos
# de la columna.
# Asigna un valor numérico a cada uno y sustituye en la columna todos por esos números. 
print(marketing['Education'].unique())
marketing.replace(to_replace='Graduation',value=0,inplace=True)
marketing.replace(to_replace='PhD',value=1,inplace=True)
marketing.replace(to_replace='Master',value=2,inplace=True)
marketing.replace(to_replace='2n Cycle',value=3,inplace=True)
marketing.replace(to_replace='Basic',value=4,inplace=True)
marketing.head(10)

['Graduation' 'PhD' 'Master' '2n Cycle' 'Basic']

C:\Users\Equipo\AppData\Local\Temp\ipykernel_1164\486289405.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  marketing.replace(to_replace='Basic',value=4,inplace=True)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died
200,7300,1952,0,Divorced,69142,0,1,2014-06-29,50,448,...,0,1,0,0,0,0,3,11,0,False
989,453,1956,1,Widow,35340,1,1,2014-06-29,1,27,...,0,0,0,0,0,0,3,11,0,False
1812,8093,1969,2,Married,79734,0,0,2014-06-28,72,572,...,0,0,0,1,0,0,3,11,0,False
796,6722,1954,1,Married,70421,0,1,2014-06-28,98,479,...,0,0,0,0,0,0,3,11,0,False
45,1371,1976,0,Single,79941,0,0,2014-06-28,72,123,...,0,0,0,0,0,0,3,11,0,False
1587,2471,1965,0,Married,61482,0,0,2014-06-27,39,48,...,0,0,0,0,0,0,3,11,0,False
1800,2831,1976,0,Together,78416,0,1,2014-06-27,99,453,...,0,0,0,0,0,0,3,11,0,False
706,4472,1970,1,Divorced,35682,1,0,2014-06-27,34,23,...,0,0,0,0,0,0,3,11,0,False
2199,9014,1975,0,Married,37085,1,1,2014-06-26,65,39,...,0,0,0,0,0,0,3,11,0,False
463,7059,1963,0,Married,80124,0,0,2014-06-26,47,483,...,1,0,0,0,0,0,3,11,0,False

In [8]:
#1.6 Filtra el dataframe para guardar uno nuevo, llamado VIP_clients. En el tienen que figurar 
# solo los clientes que tengan MntWines mayor que 400 e income mayor que 80000. 
# Cuando te encuentres problemas, los tienes que solucionar usando el propio dataframe, no
# directamente en el csv. Dependiendo de como lo quieras hacer puede que tengas que comprobar 
# el tipo de algún objeto. Dicha comparación se hace así: type(objeto) == str

incomes = []
for index,row in marketing.iterrows():
    if (type(row['Income']) == str):
        incomes.append(float(row['Income'].replace(",","")))
    else:
        incomes.append(row['Income'])


marketing['Income'] = incomes
VIP_clients = marketing.loc[(marketing['MntWines']>400) & (marketing['Income']>80000)]
VIP_clients.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Probably_Died
463,7059,1963,0,Married,80124.0,0,0,2014-06-26,47,483,...,1,0,0,0,0,0,3,11,0,False
266,1225,1963,0,Married,80124.0,0,0,2014-06-26,47,483,...,1,0,0,0,0,0,3,11,0,False
1269,9400,1958,3,Single,85485.0,0,0,2014-06-21,73,630,...,0,0,0,0,0,0,3,11,0,False
1710,477,1986,0,Married,83512.0,0,0,2014-06-17,31,1060,...,1,0,1,1,1,0,3,11,1,False
53,2225,1977,0,Divorced,82582.0,0,0,2014-06-07,54,510,...,1,0,0,1,0,0,3,11,1,False

In [9]:
nba = pd.read_csv('nba.csv')
nba.iloc[0]

Rk              1
Team    Utah Jazz
G              47
MP          240.0
FG           40.7
FGA          86.3
FG%         0.472
3P           14.7
3PA          40.6
3P%         0.362
2P           26.1
2PA          45.7
2P%         0.571
FT           18.1
FTA          23.2
FT%          0.78
ORB          10.3
DRB          36.3
TRB          46.6
AST          22.2
STL           6.9
BLK           4.9
TOV          14.1
PF           18.9
PTS         114.2
Name: 0, dtype: object

In [10]:
# 2.2 Filtra el dataframe y quédate solo con los equipos que tinen más de 45 partidos jugados (G)
#  y más de 13 triples por partido (3P)
nba_nuevo = nba.loc[(nba['G']>45) & (nba['3P']>13)]
nba_nuevo

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Utah Jazz,47,240.0,40.7,86.3,0.472,14.7,40.6,0.362,...,0.780,10.3,36.3,46.6,22.2,6.9,4.9,14.1,18.9,114.2
1,2,Charlotte Hornets,47,242.1,42.5,92.3,0.461,14.0,38.2,0.367,...,0.736,10.6,33.9,44.4,27.1,8.8,5.1,13.1,19.3,114.1
4,5,Milwaukee Bucks,49,241.0,40.4,89.2,0.454,14.3,39.5,0.362,...,0.778,10.4,36.8,47.2,23.0,7.7,4.4,13.8,17.9,112.0
8,9,Minnesota Timberwolves,46,241.6,40.4,91.6,0.441,14.3,41.7,0.343,...,0.759,12.4,32.8,45.2,24.5,8.8,5.8,15.1,22.1,111.0
12,13,Golden State Warriors,47,241.1,39.9,86.2,0.463,14.1,39.8,0.354,...,0.756,9.9,36.4,46.3,27.5,9.5,5.0,15.6,20.3,109.4
13,14,Miami Heat,47,241.1,39.4,85.5,0.460,13.5,36.0,0.376,...,0.807,10.8,33.7,44.5,25.7,7.3,3.3,14.4,20.1,108.6
14,15,Portland Trail Blazers,46,240.5,38.8,86.7,0.448,13.6,37.9,0.359,...,0.770,10.1,33.7,43.8,22.7,7.7,4.8,14.0,19.9,108.4
15,16,Houston Rockets,47,240.5,38.7,85.7,0.452,13.3,38.4,0.347,...,0.717,9.5,33.6,43.1,22.9,7.3,4.8,16.9,20.1,108.3

In [11]:
# Muestra el nombre de los equipos que tienen mal calculados los puntos por partido. 
# Es decir, que no coincida la columna de puntos por partido (PTS) con el cálculo:
# 3*3P + 2*2P + FT
for index,row in nba.iterrows():
    if (float(row['PTS'])) != float(row['3P'])*3+float(row['2P'])*2+float(row['FT']):
        print(row['Team'])

Utah Jazz
Charlotte Hornets
Phoenix Suns
Brooklyn Nets
Milwaukee Bucks
Memphis Grizzlies
Atlanta Hawks
Minnesota Timberwolves
Sacramento Kings
Chicago Bulls
Portland Trail Blazers
Houston Rockets
Indiana Pacers
Denver Nuggets
Washington Wizards
Boston Celtics
Cleveland Cavaliers
Toronto Raptors
Los Angeles Clippers
Dallas Mavericks
New York Knicks
Orlando Magic
Detroit Pistons
Oklahoma City Thunder

In [12]:
# En un dataframe nuevo quita las columnas Rk, Team y PTS. Después, muestra la matriz
# de correlación solo de la columna 2P. Muestra los 5 que mayor correlación tengan.

In [ ]:
nba.drop(['Rk','Team','PTS'],inplace=True,axis=1)
nba.corr(numeric_only=True)['2P'].abs().sort_values(ascending=False)[1:6]

2PA    0.864277
FG     0.813984
3PA    0.738197
3P     0.605198
FG%    0.588684
Name: 2P, dtype: float64